site_name: SPO JAPAN GUILD DOCS
site_url: https://docs.spojapanguild.net
site_description: SPO JAPAN GUILD監修のステークプール構築ガイド。私たちは日本におけるステークプール構築を促進しカルダノ分散化に貢献してまいります。
theme:
  language: ja
  favicon: images/favicon.png
  logo: images/logo-white.png
  font:
    text: Noto Sans JP
  name: material
  custom_dir: docs/overrides
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      accent: cyan
      primary: cyan
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  features:
    - content.tabs.link
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.instant
    - navigation.tracking
    - navigation.footer
    - navigation.path
    - navigation.expand
    - search.suggest
    - search.highlight
    - search.share
    - content.code.copy
    - content.code.annotate
  icon:
    repo: fontawesome/brands/github

copyright: Copyright &copy; 2020 - 2026 CARDANO COMMUNITY SPO JAPAN GUILD
repo_url: https://github.com/btbf/spojapanguild
repo_name: btbf/spojapanguild

plugins:
  - git-revision-date-localized:
      type: datetime
  - search:
      lang: ja

extra:
  generator: false
  analytics:
    provider: google
    property: G-R9C48XMXE5
  consent:
    title: Cookieの使用許諾
    description: >- 
      当サイトは、ドキュメントの効果測定や利用者確認のため、クッキーを使用しGoogle アナリティクスによるトラフィックの分析を行っています。
      ご同意いただける場合は「Accept」をクリックしてください。

    cookies:
      analytics: Google Analytics
  social:
    - icon: fontawesome/brands/x-twitter
      link: https://x.com/spojapanguild
      name: X
    - icon: fontawesome/solid/house
      link: https://spojapanguild.net/
      name: Homepage


markdown_extensions:
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - footnotes
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - tables
  - attr_list
  - md_in_html
  - toc:
      permalink: true
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

extra_css:
  - stylesheets/extra.css

nav:
    - 'HOME':
      - 'はじめに': './index.md'
      - 'Cardano':
        - 'ステークプール':
          - '構築':
              - '・ 概要': './cardano/setup/index.md'
          - '運用':
            - '・ 概要': './cardano/operation/index.md'
        - 'SPOニュースレター登録': './spo-newsletter.md'
      - 'Midnight':
        - 'バリデーター':
          - '・ 概要': './midnight/index.md'
      - 'SPO JAPAN GUILD':
        - 'SJG関連':
          - '・ SJGラーニング': './sjg/learning.md'
          - '・ 貢献者': './sjg/contributors.md'
          - '・ 寄付とクレジット': './sjg/donation-credit.md'
      - '更新履歴': './changelogs.md'

    - 'Cardano':
      - 'ステークプール':
        - '構築':
          - '・ 概要': './cardano/setup/index.md'
          - '手順':
            - '1. エアギャップ環境構築': './cardano/setup/air-gapped-setup.md'
            - '2. Ubuntu初期設定': './cardano/setup/ubuntu-setup.md'
            - '3. ノードセットアップ': './cardano/setup/node-setup.md'
            - '4. リレー/BP接続設定': './cardano/setup/relay-bp-setup.md'
            - '5. BP用キー生成': './cardano/setup/bp-key-setup.md'
            - '6. アドレス生成': './cardano/setup/address-generate.md'
            - '7. ステークアドレス登録': './cardano/setup/stake-address-register.md'
            - '8. ステークプール登録': './cardano/setup/stake-pool-register.md'
            - '9. 最終チェック': './cardano/setup/final-checks.md'
            - '10. 監視ツール設定': './cardano/setup/monitoring-setup.md'
            - '11. ブロックログ設定': './cardano/setup/blocklog-setup.md'
            - '12. SPO BlockNotify設定': './cardano/setup/blocknotify-setup.md'
        - '運用':
          - '・ 概要': './cardano/operation/index.md'
          - '定常運用':
            - '・ KESの更新': './cardano/operation/kes-update.md'
            - '・ ノードアップデート': './cardano/operation/node-update.md'
          - '必要時運用':
            - '・ 資金引き出し': './cardano/operation/withdrawal.md'
            - '・ 運用証明書の更新': './cardano/operation/cert-update.md'
          - '鍵・権限管理':
            - '・ Calidusキー生成': './cardano/operation/calidus-key-generation.md'
          - 'ノード・サーバー管理':
            - 'ノード管理':
              - '・ リレーノード増設': './cardano/operation/add-relay.md'
              #- '・ BPポート変更': './cardano/operation/bp-port-change.md'
            - 'サーバー管理':
              - '移行':
                - '・ リレーサーバー移行': './cardano/operation/relay-migration.md'
                - '・ BPサーバー移行': './cardano/operation/bp-migration.md'
                #- '・ サーバー間転送設定':
                #- '・ 事前設定': './cardano/operation/rsync-ssh.md'
                #- '・ ファイル転送手順': './cardano/operation/transfer.md'
                - '・ Ubuntu22.04移行': './cardano/operation/ubuntu22-migration.md'
            - 'Mithril':
              - '・ DB同期(Mithril)': './cardano/operation/mithril-client.md'
              - '・ Mithril Signerノードの設定、更新': './cardano/operation/mithril-signer-node-setup-and-updates.md'
          - '運用ツール':
            - '導入':
              - '・ SJGツール導入設定': './cardano/operation/sjg-tool-setup.md'
            - '設定':
              - '・ SFTPソフト設定': './cardano/operation/sftp-setup.md'
              - 'Grafana追加設定':
                - '・ Grafanaセキュリティ強化': './cardano/operation/grafana-security.md'
                - '・ Grafanaアラート設定': './cardano/operation/grafana-alert.md'
                - '・ Grafanaリポジトリ変更': './cardano/operation/grafana-repo.md'
            - '移行':
              - '・ SPOBlockNotify移行手順': './cardano/operation/blocknotify-reinstall.md'
          - 'ガバナンス':
            - '・ ガバナンスアクションSPO投票': './cardano/operation/gov-spo-vote.md'
            - '・ カタリスト有権者登録': './cardano/operation/catalyst-voting.md'
          - '一覧':
            - '・ 各種コマンド': './cardano/operation/linux-commands.md'
          - '廃止処理':
            - '・ プール廃止処理': './cardano/operation/pool-retire.md'
        - 'よくある質問':
          - '運用編':
            - '・ ノード関連': './cardano/faq/node.md'
            - '・ ブロックログ関連': './cardano/faq/blocklog.md'
            - '・ ノード監視関連': './cardano/faq/monitoring.md'
    - 'Midnight':
      - 'バリデーター':
        - '・ 概要': './midnight/index.md'
        - '構築':
          - '・ Cardanoインデクサーサーバー構築': './midnight/setup/cardano-indexer-setup.md'
          - '・ Midnightノード稼働サーバー構築': './midnight/setup/midnight-node-server-setup.md'
          - '・ Midnightノード起動': './midnight/setup/start-midnight-node.md'
        - '一覧':
          - '・ Midnightノードオプション一覧': './midnight/operation/midnight-node-options.md'
      # - 'エアドロップ申請':
        # - '・ Glacier Drop': './midnight/midnight-glacier-drop.md'
    - 'SPO JAPAN GUILD':
      - 'SJG関連':
        - '・ SJGラーニング': './sjg/learning.md'
        - '・ 貢献者': './sjg/contributors.md'
        - '・ 寄付とクレジット': './sjg/donation-credit.md'