site_name: SPO JAPAN GUILD DOCS
site_url: https://docs.spojapanguild.net
site_description: SPO JAPAN GUILD監修のステークプール構築ガイド。私たちは日本におけるステークプール構築を促進しカルダノ分散化に貢献してまいります。
theme:
  language: ja
  favicon: images/favicon.png
  logo: images/logo-white.png
  font:
    text: Noto Sans JP
  name: material
  custom_dir: docs/overrides
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      accent: cyan
      primary: cyan
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  features:
    - content.tabs.link
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.instant
    - navigation.tracking
    - navigation.footer
    - navigation.path
    - search.suggest
    - search.highlight
    - search.share
    - content.code.copy
    - content.code.annotate
  icon:
    repo: fontawesome/brands/github

copyright: Copyright &copy; 2020 - 2025 CARDANO COMMUNITY SPO JAPAN GUILD
repo_url: https://github.com/btbf/spojapanguild
repo_name: btbf/spojapanguild

plugins:
  - git-revision-date-localized:
      type: datetime
  - search:
      lang: ja

extra:
  generator: false
  analytics:
    provider: google
    property: G-R9C48XMXE5
  consent:
    title: Cookieの使用許諾
    description: >- 
      当サイトは、ドキュメントの効果測定や利用者確認のため、クッキーを使用しGoogle アナリティクスによるトラフィックの分析を行っています。
      ご同意いただける場合は「Accept」をクリックしてください。

    cookies:
      analytics: Google Analytics


markdown_extensions:
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - footnotes
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - tables
  - attr_list
  - md_in_html
  - toc:
      permalink: true
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

extra_css:
  - stylesheets/extra.css

nav:
    - 'HOME':
      - 'はじめに': './index.md'
      - 'プール構築マニュアル': './setup/index.md'
      - 'プール運用マニュアル': './operation/index.md'
      - 'SJGラーニング': ./learning.md
      - '更新履歴': './changelogs.md'
      - '貢献者': './contributors.md'
      - '寄付とクレジット': './setup/donation-credit.md'

    - 'プール構築マニュアル':
      - '構築マニュアル': './setup/index.md'
      - '1. エアギャップ環境セットアップ': './setup/air-gapped-setup.md'
      - '2. Ubuntu初期設定': './setup/ubuntu-setup.md'
      - '3. ノードインストール': './setup/node-setup.md'
      - '4. リレー/BPの接続': './setup/relay-bp-setup.md'
      - '5. BP用キー生成': './setup/bp-key-setup.md'
      - '6. アドレス生成': './setup/address-generate.md'
      - '7. ステークアドレス登録': './setup/stake-address-register.md'
      - '8. ステークプール登録': './setup/stake-pool-register.md'
      - '9. 最終チェック': './setup/final-checks.md'
      - '10. 監視ツール設定': './setup/monitoring-setup.md'
      - '11. ブロックログ設定': './setup/blocklog-setup.md'
      - '12. SPO BlockNotify設定': './setup/blocknotify-setup.md'
      - 'SPOニュースレター登録': './setup/spo-newsletter.md'
      - '寄付とクレジット': './setup/donation-credit.md'
    - 'プール運用マニュアル':
      - '運用マニュアル': './operation/index.md'
      - '1. プールオペレーション':
        - '1-1. KESの更新': './operation/kes-update.md'
        - '1-2. 運用証明書の更新': './operation/cert-update.md'
        - '1-3. 資金引き出し': './operation/withdrawal.md'
        - '1-4. Calidusキー生成': './operation/calidus-key-generation.md'
        - '1-5. プール廃止処理': './operation/pool-retire.md'
      - '2. ノード管理':
        - '2-1. ノードアップデート': './operation/node-update.md'
        - '2-2. DB同期(Mithril)':  './operation/mithril-client.md'
        - '2-3. リレーノード増設': './operation/add-relay.md'
        - '2-4. BPポート変更': './operation/bp-port-change.md'
      - '3. サーバー管理':
        # - '3-1. サーバー間転送設定':
        #   - '事前設定': './operation/rsync-ssh.md'
        #   - 'ファイル転送手順': './operation/transfer.md'
        - '3-1. Ubuntu22.04移行': './operation/ubuntu22-migration.md'
        - '3-2. サーバー移行':
          - 'リレーサーバー移行': './operation/relay-migration.md'
          - 'BPサーバー移行': './operation/bp-migration.md'
      - '4. ツール設定':
        - '4-1. SJGツール導入設定': './operation/sjg-tool-setup.md'
        - '4-2. SFTPソフト設定': './operation/sftp-setup.md'
        - '4-3. Grafana追加設定':
          - 'Grafanaセキュリティ強化': './operation/grafana-security.md'
          - 'Grafanaアラート設定': './operation/grafana-alert.md'
          - 'Grafanaリポジトリ変更': './operation/grafana-repo.md'
        - '4-4. SPOBlockNotify移行手順': './operation/blocknotify-reinstall.md'
      - '5. ガバナンス':
          - 'ガバナンスアクションSPO投票': './operation/gov-spo-vote.md'
          - 'カタリスト有権者登録': './operation/catalyst-voting.md'
      - '6. Midnight関連':
        - 'Glacier Drop請求手続き': './operation/midnight-glacier-drop.md'
      - '7. Linuxコマンド集': './operation/linux-commands.md'
    - 'SJGラーニング': './learning.md'
    - 'よくある質問':
      - '運用編':
        - 'ノード関連': './faq/node.md'
        - 'ブロックログ関連': './faq/blocklog.md'
        - 'ノード監視関連': './faq/monitoring.md'