site_name: SPO JAPAN GUILD DOCS
site_url: https://docs.spojapanguild.net
site_description: SPO JAPAN GUILD監修のステークプール構築ガイド。私たちは日本におけるステークプール構築を促進しカルダノ分散化に貢献してまいります。
theme:
  language: ja
  favicon: images/favicon.png
  logo: images/logo-white.png
  font:
    text: Noto Sans JP
  name: material
  custom_dir: docs/overrides
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      accent: cyan
      primary: cyan
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  features:
    - content.tabs.link
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.instant
    - navigation.tracking
    - navigation.footer
    - navigation.path
    - navigation.expand
    - search.suggest
    - search.highlight
    - search.share
    - content.code.copy
    - content.code.annotate
  icon:
    repo: fontawesome/brands/github

copyright: Copyright &copy; 2020 - 2025 CARDANO COMMUNITY SPO JAPAN GUILD
repo_url: https://github.com/btbf/spojapanguild
repo_name: btbf/spojapanguild

plugins:
  - git-revision-date-localized:
      type: datetime
  - search:
      lang: ja

extra:
  generator: false
  analytics:
    provider: google
    property: G-R9C48XMXE5
  consent:
    title: Cookieの使用許諾
    description: >- 
      当サイトは、ドキュメントの効果測定や利用者確認のため、クッキーを使用しGoogle アナリティクスによるトラフィックの分析を行っています。
      ご同意いただける場合は「Accept」をクリックしてください。

    cookies:
      analytics: Google Analytics


markdown_extensions:
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - footnotes
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - tables
  - attr_list
  - md_in_html
  - toc:
      permalink: true
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

extra_css:
  - stylesheets/extra.css

nav:
    - 'HOME':
      - 'はじめに': './index.md'
      - 'プール構築マニュアル': './setup/index.md'
      - 'プール運用マニュアル': './operation/index.md'
      - 'SJGラーニング': ./learning.md
      - '更新履歴': './changelogs.md'
      - '貢献者': './contributors.md'
      - '寄付とクレジット': './setup/donation-credit.md'

    - 'プール構築マニュアル':
      - '構築マニュアル': './setup/index.md'
      - 'プール構築':
        - '1. エアギャップ環境構築': './setup/air-gapped-setup.md'
        - '2. Ubuntu初期設定': './setup/ubuntu-setup.md'
        - '3. ノードセットアップ': './setup/node-setup.md'
        - '4. リレー/BP接続設定': './setup/relay-bp-setup.md'
        - '5. BP用キー生成': './setup/bp-key-setup.md'
        - '6. アドレス生成': './setup/address-generate.md'
        - '7. ステークアドレス登録': './setup/stake-address-register.md'
        - '8. ステークプール登録': './setup/stake-pool-register.md'
        - '9. 最終チェック': './setup/final-checks.md'
        - '10. 監視ツール設定': './setup/monitoring-setup.md'
        - '11. ブロックログ設定': './setup/blocklog-setup.md'
        - '12. SPO BlockNotify設定': './setup/blocknotify-setup.md'
      - 'SPOニュースレター登録': './setup/spo-newsletter.md'
      - '寄付とクレジット': './setup/donation-credit.md'
    - 'プール運用マニュアル':
      - '運用マニュアル': './operation/index.md'
      - 'プール運用':
        - '・ KESの更新': './operation/kes-update.md'
        - '・ 運用証明書の更新': './operation/cert-update.md'
        - '・ 資金引き出し': './operation/withdrawal.md'
        - '・ Calidusキー生成': './operation/calidus-key-generation.md'
        - '・ プール廃止処理': './operation/pool-retire.md'
      - 'ノード管理':
        - '・ ノードアップデート': './operation/node-update.md'
        - '・ DB同期(Mithril)':  './operation/mithril-client.md'
        - '・ リレーノード増設': './operation/add-relay.md'
        - '・ BPポート変更': './operation/bp-port-change.md'
      - 'サーバー管理':
        # - '・ サーバー間転送設定':
        #   - '・ 事前設定': './operation/rsync-ssh.md'
        #   - '・ ファイル転送手順': './operation/transfer.md'
        - '・ Ubuntu22.04移行': './operation/ubuntu22-migration.md'
        - '・ サーバー移行':
          - '・ リレーサーバー移行': './operation/relay-migration.md'
          - '・ BPサーバー移行': './operation/bp-migration.md'
      - '運用ツール':
        - '・ SJGツール導入設定': './operation/sjg-tool-setup.md'
        - '・ SFTPソフト設定': './operation/sftp-setup.md'
        - '・ Grafana追加設定':
          - '・ Grafanaセキュリティ強化': './operation/grafana-security.md'
          - '・ Grafanaアラート設定': './operation/grafana-alert.md'
          - '・ Grafanaリポジトリ変更': './operation/grafana-repo.md'
        - '・ SPOBlockNotify移行手順': './operation/blocknotify-reinstall.md'
      - 'ガバナンス':
          - '・ ガバナンスアクションSPO投票': './operation/gov-spo-vote.md'
          - '・ カタリスト有権者登録': './operation/catalyst-voting.md'
      - 'Mithril関連':
        - '・ Mithril Signerノードの設定、更新': './operation/mithril-signer-node-setup-and-updates.md'
      - 'Midnight関連':
        - '・ Glacier Drop請求手続き': './operation/midnight-glacier-drop.md'
      - 'Linuxコマンド集':
        - '・ 各種コマンド': './operation/linux-commands.md'
    - 'Midnightバリデータ':
      - '構築マニュアル概要': './midnight/index.md'
      - 'Cardanoインデクサ用サーバ構築': './midnight/db-sync-setup.md'
      - 'Midnightノード用サーバ構築': './midnight/register-spo.md'
      - 'Midnightノード起動': './midnight/setup-midnight-node.md'
      - 'ノードオプション一覧': './midnight/node-options.md'
    - 'SJGラーニング': './learning.md'
    - 'よくある質問':
      - '運用編':
        - '・ ノード関連': './faq/node.md'
        - '・ ブロックログ関連': './faq/blocklog.md'
        - '・ ノード監視関連': './faq/monitoring.md'